#!/bin/bash
set -e
export git_path=$(git rev-parse --show-toplevel)
ln -s $git_path/git_hooks/commit-msg $git_path/.git/hooks/commit-msg
ln -s $git_path/git_hooks/pre-commit $git_path/.git/hooks/pre-commit
